version: "3"
services:
  reverseproxy:
      image: guilhermecamacho/udagram-reverse-proxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - udagram-user-api
        - udagram-feed-api     
  udagram-user-api:
    image: guilhermecamacho/udagram-user-api
    container_name: user-api
    ports:
        - 8081:8081
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME : $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  udagram-feed-api:
    image: guilhermecamacho/udagram-feed-api
    container_name: feed-api
    ports:
        - 8082:8082
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: guilhermecamacho/udagram-frontend
    ports:
      - "8100:80"
