apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-user-api
  name: udagram-user-api-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-user-api-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: udagram-user-api
