apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-feed-api
  name: udagram-feed-api
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-feed-api
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: udagram-feed-api
